### PR TITLE
Added npx to docker files and added a shell script.

### PR DESCRIPTION
**Pull request by dagomar**
This is a feature request for adding npx to the mix. With npx it becomes possible to run npm global commands without installing them globally, which doesn't work in this docker setup. I've been running this locally with a modified Dockerfile with great success, I think it would make a great improvement for this project. 

As a todo: I think this will need to also add test scripts, I am willing to do so, but perhaps @mkenney  could first have a look at the feature request and what he thinks about it.

### CODE REVIEW

**Comment by mkenney** [comment]
The tests are failing because the changes trigger a test build of each image and `travis-ci` times out after an hour :) All the images that did build did pass just fine though.

Another issue is that the http://hub.docker.com/ builds are **very** slow and also enforce a 60 minute timeout, and building Node from source in the `alpine` images takes longer than that in that build system. I've been thinking about switching to the official Node `alpine` base images for that reason, when I have a chance I'll experiment with one of the builds. That may solve both issues.

**Comment by mkenney** [comment]
@dagomar I finally got back to this. I've updated the `alpine` builds and merged the changes into your branch. I'll check on the build later.

**Comment by mkenney** [comment]
Hi @dagomar, I think everything looks good, the last thing this needs is a test script. If you can put one together that would be awesome (let me know and I'll explain how they work), otherwise I'll add one when I get a chance.

**Comment by jgoux** [comment]
I can't wait for this being merged! 🎊

**Pull request merged**
