### PR TITLE
Remove run-as-user command because it is also the entrypoint

### PR DESCRIPTION
**Pull request by dagomar**
I found that when using the provided shell scripts the docker container fails to run the desired command. Instead the command that is send to the container is:

`
/run-as-user /run-as-user /usr/local/bin/{script} [...]`

I was able to see with 'top' that the above was the command which was running without ever finishing. Removing the /run-as-user from the shell scripts worked for me.

### CODE REVIEW

**Comment by dagomar** [comment]
Not sure why the build failed, it stalled after pulling the image. Can I rerun the test?

**Comment by dagomar** [comment]
Upon further investigation I noticed that these shell scripts are mimicked in the test folder. Perhaps I should update those as well?

**Comment by mkenney** [comment]
Hi, thanks for the PR! That command is leftover from the transition of that script from optional to an entrypoint, I think it looks good. I'm not sure why the build failed, it may have just stalled out, I restarted it and if it fails again I'll take a closer look.

I do think it would be good to update the `/test` scripts to match so everything is consistent, thanks!

**Comment by mkenney** [comment]
So I took a look and the `/run-as-user` script does need to be removed in the test files as well:
```
test/bower.sh
test/grunt.sh
test/gulp.sh
test/md.sh
test/node.sh
test/npm.sh
test/yarn.sh
```
If you wouldn't mind adding that to this PR that would be great, thank you!

**Comment by dagomar** [comment]
Hi @mkenney,

I don't mind, I'll update it later today!

Greets,

Dagomar

**Comment by dagomar** [comment]
Couple of days later, but I made the change to the test files :)

**Comment by mkenney** [comment]
Awesome, thank you!

**Pull request merged**
